blog/urls.py
from django.urls import path
from .views import BlogListView, BlogCreateView


app_name="blog"

urlpatterns = [
    path('', BlogListView.as_view(), name="home"),
    path('create/', BlogCreateView.as_view(), name="create"),
    path('error/', BlogCreateView.as_view(), name="error")
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('blog/', include('blog.urls', namespace='blog'))
]

blog/models.py
from django.db import models

# Create your models here.

class Post(models.Model):
    title=models.CharField(max_length=250)
    content=models.TextField()

    def __str__(self):
        return self.title

blog/forms.py
from dataclasses import fields
from django import forms

from .models import Post

class PostCreateForm(forms.ModelForm):
    class Meta:
        model=Post
        fields=('title','content')

blog/views.py
from django.shortcuts import render, redirect
from django.views.generic import View
from .forms import PostCreateForm
from .models import Post

# Create your views here.

class BlogListView(View):
    def get(self, request, *args, **kwargs):
        posts = Post.objects.all()
        context = {
            'posts':posts
        }
        return render(request, 'blog_list.html', context)


class BlogCreateView(View):
    def get(self, request, *args, **kwargs):
        form=PostCreateForm()
        context = {
            'form':form
        }
        return render(request, 'blog_create.html',context)

    def post(self, request, *args, **kwargs):
        if request.method=="POST":
            form = PostCreateForm(request.POST)
            if form.is_valid():
                title = form.cleaned_data.get('title')
                content = form.cleaned_data.get('content')
                p, created = Post.objects.get_or_create(title=title, content=content)
                p.save()
                return redirect('blog:home')
            else:
                return render(request, 'error.html',context)
                
        context = {
        }
        return render(request, 'blog_create.html',context)    


class BlogDetailView(View):
    def get(self, request, *args, **kwargs):
        context = {
            
        }
        return render(request, 'blog_detail.html', context)

core/views.py
from multiprocessing import context
from django.views.generic import View
from django.shortcuts import render

class HomeView(View):
    def get(self, request, *args, **kwargs):
        context={

        }
        return render(request, 'index.html', context)

templates/blog_create.html
<form method="POST">
    {% csrf_token %}
    Titulo {{form.title}}
    <br>
    contenido {{form.content}}
    <button type="submit">Enviar</button>
</form>

templates/blog_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Aqui es el blog list</h2>
    <br>
    {%for post in posts%}
    {{post.title}}
    {%endfor%}
    <br>
    <a href="{%url 'blog:create'%}">Crear Articulo<a>
</body>
</html>

templates/error.html
upssssss errorrrrrr

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Hola, visita mi blog <a href="{%url 'blog:home' %}">blog aqui</a></h2>
</body>
</html>